# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - moses-ecss-data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run:  pip install -r djangoPython/djangoPython/requirements.txt
        
      - name: Install corsheader
        run:  pip install django-cors-headers

      - name: Install inflect
        run: pip install inflect
      
      - name: Install pymongo
        run: pip install pymongo
            
      - name: Run collectstatic
        run: python djangoPython/manage.py collectstatic --noinput
          
  
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_051E17E589364024BFB97CF759C7F345 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A27BD6CA3AA040CFB4E84DF1206A87AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A604BDBE12B74590AC43060CB32C5190 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'moses-ecss-data'
          slot-name: 'Production'
      
      - name: Install dependencies
        run: pip install -r djangoPython/djangoPython/requirements.txt

      - name: Install inflect
        run: pip install inflect

      - name: Install pymongo
        run: pip install pymongo
            
      - name: Install corsheader
        run:  pip install django-cors-headers
  
      - name: Run collectstatic
        run: python djangoPython/manage.py collectstatic --noinput
  
          